language: rust
sudo: required
rust:
- nightly
- beta
- 1.6.0
addons:
  postgresql: 9.4
before_script:
- "./.travis/setup.sh"
script:
- cargo test
- cargo test --features "uuid rustc-serialize time unix_socket serde_json chrono openssl bit-vec eui48 num"
