[package]
name = "tokio-postgres-openssl"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]

[dependencies]
bytes = "0.4"
futures = "0.1"
openssl = "0.10"
tokio = "0.1.9"
tokio-openssl = "0.2"
tokio-postgres = { version = "0.3", path = "../tokio-postgres" }
